# Netlify configuration for a Next.js project

[build]
  # Command to build the Next.js application
  command = "npm run build"

  # Directory where the built assets are located
  # For Next.js, this is typically the .next directory
  publish = ".next"

[build.environment]
  # Set the Node.js version to be used by Netlify
  # This should match the version specified in .nvmrc if it exists
  NODE_VERSION = "20"

[functions]
  # Directory where serverless functions are located
  # This is important for Next.js API routes and server-side rendering
  directory = ".next/functions"

# The Netlify Next.js plugin is essential for handling SSR, ISR, Image Optimization, etc.
# It is usually installed automatically by Netlify's build system when it detects a Next.js project.
# If you need to add it manually, you can do so in the Netlify UI under "Build & deploy" > "Plugins".
# [[plugins]]
#  package = "@netlify/plugin-nextjs"
